Task3
NPeganov/netology-python-1-loops2 pull request #3
Opened 2023-06-13 17:13 UTC by Dwwwarfff

2023-06-14 00:21 UTC, Dwwwarfff reviewed
Isn't everything ok here?

2023-06-19 20:26 UTC, NPeganov requested changes

2023-06-19 20:26 UTC, NPeganov commented on task3.py
> +        val[ROI_KEY] = ROI_calc(val['revenue'], val['cost'])
As soon as we have ROI_KEY here, why shouldn't we have the same for 'revenue' and 'cost'? Let's make it consistent.

2023-06-21 15:57 UTC, NPeganov approved these changes

2023-06-21 16:19 UTC, merged